apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: null
    # Hier node eingefügt damit jupyter-db als Pod starten kann
    volume.kubernetes.io/selected-node: labpc
    local.path.provisioner/selected-node: labpc
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  name: jupyterhub-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
